package nl.amis.bth.model.common;

import oracle.jbo.Row;
import oracle.jbo.domain.BlobDomain;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 01 12:18:04 CEST 2016
// ---------------------------------------------------------------------
public interface BthDocumentViewRow extends Row {
    Long getId();

    void setId(Long value);

    String getName();

    void setName(String value);

    String getContentType();

    void setContentType(String value);

    BlobDomain getContentData();

    void setContentData(BlobDomain value);

    String getDescription();

    void setDescription(String value);

    Long getMasterId();

    void setMasterId(Long value);
}

