package nl.amis.bth.model.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Apr 23 17:10:38 CEST 2016
// ---------------------------------------------------------------------
public interface BthPlanningItemView extends ViewObject {
    void execPlanSession(Integer pimId, Integer ssnId);
}

