package nl.amis.bth.model.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 24 12:19:48 CEST 2016
// ---------------------------------------------------------------------
public interface BthTagBindingView extends ViewObject {
    void execTagsToSession(String tags, Integer ssnId);
}

