package nl.amis.bth.model.common;

import oracle.jbo.Row;
import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 01 12:42:09 CEST 2016
// ---------------------------------------------------------------------
public interface DocumentAccessView extends ViewObject {
    void setbind_DocumentId(oracle.jbo.domain.Number value);

    Row getImageById(oracle.jbo.domain.Number aId);
}

