package nl.amis.bth.model.common;

import java.lang.Integer;
import java.lang.Long;
import java.lang.String;

import java.math.BigDecimal;
import java.math.BigInteger;

import java.sql.SQLException;
import java.sql.Timestamp;

import oracle.jbo.JboException;
import oracle.jbo.StructureDef;
import oracle.jbo.domain.DatumFactory;
import oracle.jbo.domain.DomainAttributeDef;
import oracle.jbo.domain.DomainInterface;
import oracle.jbo.domain.DomainOwnerInterface;
import oracle.jbo.domain.DomainStructureDef;
import oracle.jbo.domain.Struct;

import oracle.sql.*;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Apr 23 09:58:47 CEST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PlanningT extends Struct {
    static ORADataFactory[] mCustDatFac = null;
    static int[] mSQLTypes = null;
    static DomainStructureDef mStructureDef = null;
    static ORADataFactory fac;

    public PlanningT(Datum value) throws SQLException {
        super(value);
    }

    public PlanningT() throws SQLException {
    }

    public static ORADataFactory getORADataFactory() {
        if (fac == null) {
            class facClass implements ORADataFactory {
                public ORAData create(Datum d, int sql_type_code) throws SQLException {
                    if (d != null) {
                        return new PlanningT(d);
                    }
                    return null;
                }
            }
            fac = new facClass();
        }
        return fac;
    }

    public int[] getAttrSQLTypes() {
        if (mSQLTypes == null) {
            mSQLTypes = buildAttrSQLTypes();
        }
        return mSQLTypes;
    }

    public StructureDef getStructureDef() {
        return mStructureDef;
    }

    public String getColumnType() {
        return "PLANNING_T";
    }

    public Long getId() {
        return (Long) getAttribute(0);
    }

    public void setId(Long value) {
        setAttribute(0, value);
    }

    public Long getRomId() {
        return (Long) getAttribute(1);
    }

    public void setRomId(Long value) {
        setAttribute(1, value);
    }

    public Long getSltId() {
        return (Long) getAttribute(2);
    }

    public void setSltId(Long value) {
        setAttribute(2, value);
    }

    public String getRoomDisplayLabel() {
        return (String) getAttribute(3);
    }

    public void setRoomDisplayLabel(String value) {
        setAttribute(3, value);
    }

    public Integer getRoomCapacity() {
        return (Integer) getAttribute(4);
    }

    public void setRoomCapacity(Integer value) {
        setAttribute(4, value);
    }

    public String getRoomLocationDescription() {
        return (String) getAttribute(5);
    }

    public void setRoomLocationDescription(String value) {
        setAttribute(5, value);
    }

    public String getSlotDisplayLabel() {
        return (String) getAttribute(6);
    }

    public void setSlotDisplayLabel(String value) {
        setAttribute(6, value);
    }

    public Timestamp getSlotStartTime() {
        return (Timestamp) getAttribute(7);
    }

    public void setSlotStartTime(Timestamp value) {
        setAttribute(7, value);
    }

    public Long getSsnId() {
        return (Long) getAttribute(8);
    }

    public void setSsnId(Long value) {
        setAttribute(8, value);
    }

    public String getSessionTitle() {
        return (String) getAttribute(9);
    }

    public void setSessionTitle(String value) {
        setAttribute(9, value);
    }

    public String getSpeakers() {
        return (String) getAttribute(10);
    }

    public void setSpeakers(String value) {
        setAttribute(10, value);
    }


    public BigDecimal getSessionDuration() {
        return (BigDecimal) getAttribute(11);
    }

    public void setSessionDuration(BigDecimal value) {
        setAttribute(11, value);
    }


    public String getTrack() {
        return (String) getAttribute(12);
    }

    public void setTrack(String value) {
        setAttribute(12, value);
    }

    public void initStructureDef() {
        DomainAttributeDef[] attrs = new DomainAttributeDef[13];
        if (mStructureDef == null) {
            attrs[0] = new DomainAttributeDef("Id", "ID", 0, Long.class, 2, "NUMERIC", 0, 10, false);
            attrs[1] = new DomainAttributeDef("RomId", "ROM_ID", 1, Long.class, 2, "NUMERIC", 0, 10, false);
            attrs[2] = new DomainAttributeDef("SltId", "SLT_ID", 2, Long.class, 2, "NUMERIC", 0, 10, false);
            attrs[3] =
                new DomainAttributeDef("RoomDisplayLabel", "ROOM_DISPLAY_LABEL", 3, String.class, 12, "VARCHAR", -127,
                                       100, false);
            attrs[4] =
                new DomainAttributeDef("RoomCapacity", "ROOM_CAPACITY", 4, Integer.class, 2, "NUMERIC", 0, 4, false);
            attrs[5] =
                new DomainAttributeDef("RoomLocationDescription", "ROOM_LOCATION_DESCRIPTION", 5, String.class, 12,
                                       "VARCHAR", -127, 2000, false);
            attrs[6] =
                new DomainAttributeDef("SlotDisplayLabel", "SLOT_DISPLAY_LABEL", 6, String.class, 12, "VARCHAR", -127,
                                       100, false);
            attrs[7] =
                new DomainAttributeDef("SlotStartTime", "SLOT_START_TIME", 7, Timestamp.class, 93, "TIMESTAMP", -127, 0,
                                       false);
            attrs[8] = new DomainAttributeDef("SsnId", "SSN_ID", 8, Long.class, 2, "NUMERIC", 0, 10, false);
            attrs[9] =
                new DomainAttributeDef("SessionTitle", "SESSION_TITLE", 9, String.class, 12, "VARCHAR", -127, 500,
                                       false);
            attrs[10] =
                new DomainAttributeDef("Speakers", "SPEAKERS", 10, String.class, 12, "VARCHAR", -127, 500, false);
            attrs[11] =
                new DomainAttributeDef("SessionDuration", "SESSION_DURATION", 11, BigDecimal.class, 2, "NUMERIC", 1, 2,
                                       false);
            attrs[12] = new DomainAttributeDef("Track", "TRACK", 12, String.class, 12, "VARCHAR", -127, 100, false);
            mStructureDef = new DomainStructureDef(attrs);
        }
    }

    public ORADataFactory[] getAttrORADataFactories() {
        if (mCustDatFac == null) {
            mCustDatFac = new ORADataFactory[13];
            mCustDatFac[0] = null;
            mCustDatFac[1] = null;
            mCustDatFac[2] = null;
            mCustDatFac[3] = null;
            mCustDatFac[4] = null;
            mCustDatFac[5] = null;
            mCustDatFac[6] = null;
            mCustDatFac[7] = null;
            mCustDatFac[8] = null;
            mCustDatFac[9] = null;
            mCustDatFac[10] = null;
            mCustDatFac[11] = null;
            mCustDatFac[12] = null;
        }
        return mCustDatFac;
    }
}

