package nl.amis.bth.model;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 01 12:12:31 CEST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BthAppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public BthAppModuleImpl() {
    }

    /**
     * Container's getter for BthPersonView1.
     * @return BthPersonView1
     */
    public ViewObjectImpl getBthPersonView1() {
        return (ViewObjectImpl) findViewObject("BthPersonView1");
    }

    /**
     * Container's getter for BthPlanningItemView1.
     * @return BthPlanningItemView1
     */
    public BthPlanningItemViewImpl getBthPlanningItemView1() {
        return (BthPlanningItemViewImpl) findViewObject("BthPlanningItemView1");
    }

    /**
     * Container's getter for BthRoomView1.
     * @return BthRoomView1
     */
    public ViewObjectImpl getBthRoomView1() {
        return (ViewObjectImpl) findViewObject("BthRoomView1");
    }

    /**
     * Container's getter for BthSessionView1.
     * @return BthSessionView1
     */
    public ViewObjectImpl getBthSessionView1() {
        return (ViewObjectImpl) findViewObject("BthSessionView1");
    }

    /**
     * Container's getter for BthSlotView1.
     * @return BthSlotView1
     */
    public ViewObjectImpl getBthSlotView1() {
        return (ViewObjectImpl) findViewObject("BthSlotView1");
    }

    /**
     * Container's getter for BthSpeakerView1.
     * @return BthSpeakerView1
     */
    public ViewObjectImpl getBthSpeakerView1() {
        return (ViewObjectImpl) findViewObject("BthSpeakerView1");
    }

    /**
     * Container's getter for BthTagBindingView1.
     * @return BthTagBindingView1
     */
    public BthTagBindingViewImpl getBthTagBindingView1() {
        return (BthTagBindingViewImpl) findViewObject("BthTagBindingView1");
    }

    /**
     * Container's getter for BthTagCategoryView1.
     * @return BthTagCategoryView1
     */
    public ViewObjectImpl getBthTagCategoryView1() {
        return (ViewObjectImpl) findViewObject("BthTagCategoryView1");
    }

    /**
     * Container's getter for BthTagView1.
     * @return BthTagView1
     */
    public ViewObjectImpl getBthTagView1() {
        return (ViewObjectImpl) findViewObject("BthTagView1");
    }

    /**
     * Container's getter for PlanningScheduleView1.
     * @return PlanningScheduleView1
     */
    public ViewObjectImpl getPlanningScheduleView1() {
        return (ViewObjectImpl) findViewObject("PlanningScheduleView1");
    }

    /**
     * Container's getter for SessionsView1.
     * @return SessionsView1
     */
    public ViewObjectImpl getSessionsView1() {
        return (ViewObjectImpl) findViewObject("SessionsView1");
    }

    /**
     * Container's getter for SpeakerSessionsView1.
     * @return SpeakerSessionsView1
     */
    public ViewObjectImpl getSpeakerSessionsView1() {
        return (ViewObjectImpl) findViewObject("SpeakerSessionsView1");
    }

    /**
     * Container's getter for SpeakerSessionsView2.
     * @return SpeakerSessionsView2
     */
    public ViewObjectImpl getSpeakerSessionsView2() {
        return (ViewObjectImpl) findViewObject("SpeakerSessionsView2");
    }

    /**
     * Container's getter for SessionsView2.
     * @return SessionsView2
     */
    public ViewObjectImpl getSessionsView2() {
        return (ViewObjectImpl) findViewObject("SessionsView2");
    }

    /**
     * Container's getter for BthSessionView2.
     * @return BthSessionView2
     */
    public ViewObjectImpl getBthSessionView2() {
        return (ViewObjectImpl) findViewObject("BthSessionView2");
    }

    /**
     * Container's getter for BthSessionView3.
     * @return BthSessionView3
     */
    public ViewObjectImpl getBthSessionView3() {
        return (ViewObjectImpl) findViewObject("BthSessionView3");
    }

    /**
     * Container's getter for BthSessionView4.
     * @return BthSessionView4
     */
    public ViewObjectImpl getBthSessionView4() {
        return (ViewObjectImpl) findViewObject("BthSessionView4");
    }

    /**
     * Container's getter for BthTagBindingView2.
     * @return BthTagBindingView2
     */
    public BthTagBindingViewImpl getBthTagBindingView2() {
        return (BthTagBindingViewImpl) findViewObject("BthTagBindingView2");
    }

    /**
     * Container's getter for BthTagBindingView3.
     * @return BthTagBindingView3
     */
    public BthTagBindingViewImpl getBthTagBindingView3() {
        return (BthTagBindingViewImpl) findViewObject("BthTagBindingView3");
    }

    /**
     * Container's getter for BthSessionView5.
     * @return BthSessionView5
     */
    public ViewObjectImpl getBthSessionView5() {
        return (ViewObjectImpl) findViewObject("BthSessionView5");
    }

    /**
     * Container's getter for BthSpeakerView2.
     * @return BthSpeakerView2
     */
    public ViewObjectImpl getBthSpeakerView2() {
        return (ViewObjectImpl) findViewObject("BthSpeakerView2");
    }

    /**
     * Container's getter for BthSpeakerView3.
     * @return BthSpeakerView3
     */
    public ViewObjectImpl getBthSpeakerView3() {
        return (ViewObjectImpl) findViewObject("BthSpeakerView3");
    }

    /**
     * Container's getter for BthSessionView6.
     * @return BthSessionView6
     */
    public ViewObjectImpl getBthSessionView6() {
        return (ViewObjectImpl) findViewObject("BthSessionView6");
    }

    /**
     * Container's getter for BthPlanningItemView2.
     * @return BthPlanningItemView2
     */
    public BthPlanningItemViewImpl getBthPlanningItemView2() {
        return (BthPlanningItemViewImpl) findViewObject("BthPlanningItemView2");
    }

    /**
     * Container's getter for BthPlanningItemView3.
     * @return BthPlanningItemView3
     */
    public BthPlanningItemViewImpl getBthPlanningItemView3() {
        return (BthPlanningItemViewImpl) findViewObject("BthPlanningItemView3");
    }

    /**
     * Container's getter for BthDocumentView1.
     * @return BthDocumentView1
     */
    public BthDocumentViewImpl getBthDocumentView1() {
        return (BthDocumentViewImpl) findViewObject("BthDocumentView1");
    }

    /**
     * Container's getter for SpeakerSessionsViewLink1.
     * @return SpeakerSessionsViewLink1
     */
    public ViewLinkImpl getSpeakerSessionsViewLink1() {
        return (ViewLinkImpl) findViewLink("SpeakerSessionsViewLink1");
    }

    /**
     * Container's getter for SessionsBthSessionsViewLink.
     * @return SessionsBthSessionsViewLink
     */
    public ViewLinkImpl getSessionsBthSessionsViewLink() {
        return (ViewLinkImpl) findViewLink("SessionsBthSessionsViewLink");
    }

    /**
     * Container's getter for SessionTagsViewLink.
     * @return SessionTagsViewLink
     */
    public ViewLinkImpl getSessionTagsViewLink() {
        return (ViewLinkImpl) findViewLink("SessionTagsViewLink");
    }

    /**
     * Container's getter for SessionTagsViewLink1.
     * @return SessionTagsViewLink1
     */
    public ViewLinkImpl getSessionTagsViewLink1() {
        return (ViewLinkImpl) findViewLink("SessionTagsViewLink1");
    }

    /**
     * Container's getter for SessionSpeakerViewLink.
     * @return SessionSpeakerViewLink
     */
    public ViewLinkImpl getSessionSpeakerViewLink() {
        return (ViewLinkImpl) findViewLink("SessionSpeakerViewLink");
    }

    /**
     * Container's getter for SessionSpeakerViewLink1.
     * @return SessionSpeakerViewLink1
     */
    public ViewLinkImpl getSessionSpeakerViewLink1() {
        return (ViewLinkImpl) findViewLink("SessionSpeakerViewLink1");
    }

    /**
     * Container's getter for SessionPimViewLink.
     * @return SessionPimViewLink
     */
    public ViewLinkImpl getSessionPimViewLink() {
        return (ViewLinkImpl) findViewLink("SessionPimViewLink");
    }

    /**
     * Container's getter for SessionPimViewLink1.
     * @return SessionPimViewLink1
     */
    public ViewLinkImpl getSessionPimViewLink1() {
        return (ViewLinkImpl) findViewLink("SessionPimViewLink1");
    }

    /**
     * Container's getter for DocumentAccessView1.
     * @return DocumentAccessView1
     */
    public DocumentAccessViewImpl getDocumentAccessView1() {
        return (DocumentAccessViewImpl) findViewObject("DocumentAccessView1");
    }

    /**
     * Container's getter for BthPersonView2.
     * @return BthPersonView2
     */
    public ViewObjectImpl getBthPersonView2() {
        return (ViewObjectImpl) findViewObject("BthPersonView2");
    }

    /**
     * Container's getter for BthDocumentView2.
     * @return BthDocumentView2
     */
    public BthDocumentViewImpl getBthDocumentView2() {
        return (BthDocumentViewImpl) findViewObject("BthDocumentView2");
    }

    /**
     * Container's getter for PersonPictureViewLink.
     * @return PersonPictureViewLink
     */
    public ViewLinkImpl getPersonPictureViewLink() {
        return (ViewLinkImpl) findViewLink("PersonPictureViewLink");
    }

    /**
     * Container's getter for BthDocumentView3.
     * @return BthDocumentView3
     */
    public BthDocumentViewImpl getBthDocumentView3() {
        return (BthDocumentViewImpl) findViewObject("BthDocumentView3");
    }

    /**
     * Container's getter for PersonPictureViewLink1.
     * @return PersonPictureViewLink1
     */
    public ViewLinkImpl getPersonPictureViewLink1() {
        return (ViewLinkImpl) findViewLink("PersonPictureViewLink1");
    }

    /**
     * Container's getter for BthTagBindingView4.
     * @return BthTagBindingView4
     */
    public BthTagBindingViewImpl getThemeTagBindings() {
        return (BthTagBindingViewImpl) findViewObject("ThemeTagBindings");
    }

    /**
     * Container's getter for SessionTagsViewLink2.
     * @return SessionTagsViewLink2
     */
    public ViewLinkImpl getSessionTagsViewLink2() {
        return (ViewLinkImpl) findViewLink("SessionTagsViewLink2");
    }
}

