package nl.amis.bth.model;

import java.sql.Timestamp;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.BlobDomain;
import oracle.jbo.domain.ClobDomain;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 24 09:02:37 CEST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BthPersonViewRowImpl extends ViewRowImpl {


    public static final int ENTITY_BTHPERSON = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Id,
        FirstName,
        LastName,
        Company,
        Country,
        EmailAddress,
        MobilePhoneNumber,
        Birthdate,
        TwitterHandle,
        LinkedinProfile,
        FacebookAccount,
        Picture,
        Biography,
        Salutation,
        CommunityTitles,
        JobTitle,
        Notes,
        BiographyString,
        SpeakerSessionsView;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int FIRSTNAME = AttributesEnum.FirstName.index();
    public static final int LASTNAME = AttributesEnum.LastName.index();
    public static final int COMPANY = AttributesEnum.Company.index();
    public static final int COUNTRY = AttributesEnum.Country.index();
    public static final int EMAILADDRESS = AttributesEnum.EmailAddress.index();
    public static final int MOBILEPHONENUMBER = AttributesEnum.MobilePhoneNumber.index();
    public static final int BIRTHDATE = AttributesEnum.Birthdate.index();
    public static final int TWITTERHANDLE = AttributesEnum.TwitterHandle.index();
    public static final int LINKEDINPROFILE = AttributesEnum.LinkedinProfile.index();
    public static final int FACEBOOKACCOUNT = AttributesEnum.FacebookAccount.index();
    public static final int PICTURE = AttributesEnum.Picture.index();
    public static final int BIOGRAPHY = AttributesEnum.Biography.index();
    public static final int SALUTATION = AttributesEnum.Salutation.index();
    public static final int COMMUNITYTITLES = AttributesEnum.CommunityTitles.index();
    public static final int JOBTITLE = AttributesEnum.JobTitle.index();
    public static final int NOTES = AttributesEnum.Notes.index();
    public static final int BIOGRAPHYSTRING = AttributesEnum.BiographyString.index();
    public static final int SPEAKERSESSIONSVIEW = AttributesEnum.SpeakerSessionsView.index();

    /**
     * This is the default constructor (do not remove).
     */
    public BthPersonViewRowImpl() {
    }

    /**
     * Gets BthPerson entity object.
     * @return the BthPerson
     */
    public EntityImpl getBthPerson() {
        return (EntityImpl) getEntity(ENTITY_BTHPERSON);
    }

    /**
     * Gets the attribute value for ID using the alias name Id.
     * @return the ID
     */
    public Long getId() {
        return (Long) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name Id.
     * @param value value to set the ID
     */
    public void setId(Long value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for FIRST_NAME using the alias name FirstName.
     * @return the FIRST_NAME
     */
    public String getFirstName() {
        return (String) getAttributeInternal(FIRSTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for FIRST_NAME using the alias name FirstName.
     * @param value value to set the FIRST_NAME
     */
    public void setFirstName(String value) {
        setAttributeInternal(FIRSTNAME, value);
    }

    /**
     * Gets the attribute value for LAST_NAME using the alias name LastName.
     * @return the LAST_NAME
     */
    public String getLastName() {
        return (String) getAttributeInternal(LASTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_NAME using the alias name LastName.
     * @param value value to set the LAST_NAME
     */
    public void setLastName(String value) {
        setAttributeInternal(LASTNAME, value);
    }

    /**
     * Gets the attribute value for COMPANY using the alias name Company.
     * @return the COMPANY
     */
    public String getCompany() {
        return (String) getAttributeInternal(COMPANY);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY using the alias name Company.
     * @param value value to set the COMPANY
     */
    public void setCompany(String value) {
        setAttributeInternal(COMPANY, value);
    }

    /**
     * Gets the attribute value for COUNTRY using the alias name Country.
     * @return the COUNTRY
     */
    public String getCountry() {
        return (String) getAttributeInternal(COUNTRY);
    }

    /**
     * Sets <code>value</code> as attribute value for COUNTRY using the alias name Country.
     * @param value value to set the COUNTRY
     */
    public void setCountry(String value) {
        setAttributeInternal(COUNTRY, value);
    }

    /**
     * Gets the attribute value for EMAIL_ADDRESS using the alias name EmailAddress.
     * @return the EMAIL_ADDRESS
     */
    public String getEmailAddress() {
        return (String) getAttributeInternal(EMAILADDRESS);
    }

    /**
     * Sets <code>value</code> as attribute value for EMAIL_ADDRESS using the alias name EmailAddress.
     * @param value value to set the EMAIL_ADDRESS
     */
    public void setEmailAddress(String value) {
        setAttributeInternal(EMAILADDRESS, value);
    }

    /**
     * Gets the attribute value for MOBILE_PHONE_NUMBER using the alias name MobilePhoneNumber.
     * @return the MOBILE_PHONE_NUMBER
     */
    public String getMobilePhoneNumber() {
        return (String) getAttributeInternal(MOBILEPHONENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for MOBILE_PHONE_NUMBER using the alias name MobilePhoneNumber.
     * @param value value to set the MOBILE_PHONE_NUMBER
     */
    public void setMobilePhoneNumber(String value) {
        setAttributeInternal(MOBILEPHONENUMBER, value);
    }

    /**
     * Gets the attribute value for BIRTHDATE using the alias name Birthdate.
     * @return the BIRTHDATE
     */
    public Timestamp getBirthdate() {
        return (Timestamp) getAttributeInternal(BIRTHDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for BIRTHDATE using the alias name Birthdate.
     * @param value value to set the BIRTHDATE
     */
    public void setBirthdate(Timestamp value) {
        setAttributeInternal(BIRTHDATE, value);
    }

    /**
     * Gets the attribute value for TWITTER_HANDLE using the alias name TwitterHandle.
     * @return the TWITTER_HANDLE
     */
    public String getTwitterHandle() {
        return (String) getAttributeInternal(TWITTERHANDLE);
    }

    /**
     * Sets <code>value</code> as attribute value for TWITTER_HANDLE using the alias name TwitterHandle.
     * @param value value to set the TWITTER_HANDLE
     */
    public void setTwitterHandle(String value) {
        setAttributeInternal(TWITTERHANDLE, value);
    }

    /**
     * Gets the attribute value for LINKEDIN_PROFILE using the alias name LinkedinProfile.
     * @return the LINKEDIN_PROFILE
     */
    public String getLinkedinProfile() {
        return (String) getAttributeInternal(LINKEDINPROFILE);
    }

    /**
     * Sets <code>value</code> as attribute value for LINKEDIN_PROFILE using the alias name LinkedinProfile.
     * @param value value to set the LINKEDIN_PROFILE
     */
    public void setLinkedinProfile(String value) {
        setAttributeInternal(LINKEDINPROFILE, value);
    }

    /**
     * Gets the attribute value for FACEBOOK_ACCOUNT using the alias name FacebookAccount.
     * @return the FACEBOOK_ACCOUNT
     */
    public String getFacebookAccount() {
        return (String) getAttributeInternal(FACEBOOKACCOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for FACEBOOK_ACCOUNT using the alias name FacebookAccount.
     * @param value value to set the FACEBOOK_ACCOUNT
     */
    public void setFacebookAccount(String value) {
        setAttributeInternal(FACEBOOKACCOUNT, value);
    }

    /**
     * Gets the attribute value for PICTURE using the alias name Picture.
     * @return the PICTURE
     */
    public BlobDomain getPicture() {
        return (BlobDomain) getAttributeInternal(PICTURE);
    }

    /**
     * Sets <code>value</code> as attribute value for PICTURE using the alias name Picture.
     * @param value value to set the PICTURE
     */
    public void setPicture(BlobDomain value) {
        setAttributeInternal(PICTURE, value);
    }

    /**
     * Gets the attribute value for BIOGRAPHY using the alias name Biography.
     * @return the BIOGRAPHY
     */
    public ClobDomain getBiography() {
        return (ClobDomain) getAttributeInternal(BIOGRAPHY);
    }

    /**
     * Sets <code>value</code> as attribute value for BIOGRAPHY using the alias name Biography.
     * @param value value to set the BIOGRAPHY
     */
    public void setBiography(ClobDomain value) {
        setAttributeInternal(BIOGRAPHY, value);
    }

    /**
     * Gets the attribute value for SALUTATION using the alias name Salutation.
     * @return the SALUTATION
     */
    public String getSalutation() {
        return (String) getAttributeInternal(SALUTATION);
    }

    /**
     * Sets <code>value</code> as attribute value for SALUTATION using the alias name Salutation.
     * @param value value to set the SALUTATION
     */
    public void setSalutation(String value) {
        setAttributeInternal(SALUTATION, value);
    }

    /**
     * Gets the attribute value for COMMUNITY_TITLES using the alias name CommunityTitles.
     * @return the COMMUNITY_TITLES
     */
    public String getCommunityTitles() {
        return (String) getAttributeInternal(COMMUNITYTITLES);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMUNITY_TITLES using the alias name CommunityTitles.
     * @param value value to set the COMMUNITY_TITLES
     */
    public void setCommunityTitles(String value) {
        setAttributeInternal(COMMUNITYTITLES, value);
    }

    /**
     * Gets the attribute value for JOB_TITLE using the alias name JobTitle.
     * @return the JOB_TITLE
     */
    public String getJobTitle() {
        return (String) getAttributeInternal(JOBTITLE);
    }

    /**
     * Sets <code>value</code> as attribute value for JOB_TITLE using the alias name JobTitle.
     * @param value value to set the JOB_TITLE
     */
    public void setJobTitle(String value) {
        setAttributeInternal(JOBTITLE, value);
    }

    /**
     * Gets the attribute value for NOTES using the alias name Notes.
     * @return the NOTES
     */
    public String getNotes() {
        return (String) getAttributeInternal(NOTES);
    }

    /**
     * Sets <code>value</code> as attribute value for NOTES using the alias name Notes.
     * @param value value to set the NOTES
     */
    public void setNotes(String value) {
        setAttributeInternal(NOTES, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BiographyString.
     * @return the BiographyString
     */
    public String getBiographyString() {
        
        return getBiography().toString();
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BiographyString.
     * @param value value to set the  BiographyString
     */
    public void setBiographyString(String value) {
        if (!(value.equals(getBiographyString()))) {
        this.lock();
          ClobDomain biography = getBiography();
          biography.setChars(value.toCharArray());
          // this last line may be necessary to signal that the biography has changed
          setBiography(biography);
        }
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SpeakerSessionsView.
     */
    public RowIterator getSpeakerSessionsView() {
        return (RowIterator) getAttributeInternal(SPEAKERSESSIONSVIEW);
    }
}

