package nl.amis.bth.model;

import java.math.BigDecimal;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.ClobDomain;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 24 11:07:46 CEST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BthSessionViewRowImpl extends ViewRowImpl {


    public static final int ENTITY_BTHSESSION = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Id,
        Title,
        Abstract1,
        TargetAudience,
        ExperienceLevel,
        Granularity,
        Duration,
        SubmissionIdentifier,
        Status,
        Demos,
        Notes,
        Cospeakers,
        AbstractString,
        BthTagBindingView,
        BthSpeakerView,
        BthPlanningItemView;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int TITLE = AttributesEnum.Title.index();
    public static final int ABSTRACT1 = AttributesEnum.Abstract1.index();
    public static final int TARGETAUDIENCE = AttributesEnum.TargetAudience.index();
    public static final int EXPERIENCELEVEL = AttributesEnum.ExperienceLevel.index();
    public static final int GRANULARITY = AttributesEnum.Granularity.index();
    public static final int DURATION = AttributesEnum.Duration.index();
    public static final int SUBMISSIONIDENTIFIER = AttributesEnum.SubmissionIdentifier.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int DEMOS = AttributesEnum.Demos.index();
    public static final int NOTES = AttributesEnum.Notes.index();
    public static final int COSPEAKERS = AttributesEnum.Cospeakers.index();
    public static final int ABSTRACTSTRING = AttributesEnum.AbstractString.index();
    public static final int BTHTAGBINDINGVIEW = AttributesEnum.BthTagBindingView.index();
    public static final int BTHSPEAKERVIEW = AttributesEnum.BthSpeakerView.index();
    public static final int BTHPLANNINGITEMVIEW = AttributesEnum.BthPlanningItemView.index();

    /**
     * This is the default constructor (do not remove).
     */
    public BthSessionViewRowImpl() {
    }

    /**
     * Gets BthSession entity object.
     * @return the BthSession
     */
    public EntityImpl getBthSession() {
        return (EntityImpl) getEntity(ENTITY_BTHSESSION);
    }

    /**
     * Gets the attribute value for ID using the alias name Id.
     * @return the ID
     */
    public Long getId() {
        return (Long) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name Id.
     * @param value value to set the ID
     */
    public void setId(Long value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for TITLE using the alias name Title.
     * @return the TITLE
     */
    public String getTitle() {
        return (String) getAttributeInternal(TITLE);
    }

    /**
     * Sets <code>value</code> as attribute value for TITLE using the alias name Title.
     * @param value value to set the TITLE
     */
    public void setTitle(String value) {
        setAttributeInternal(TITLE, value);
    }

    /**
     * Gets the attribute value for ABSTRACT using the alias name Abstract1.
     * @return the ABSTRACT
     */
    public ClobDomain getAbstract1() {
        return (ClobDomain) getAttributeInternal(ABSTRACT1);
    }

    /**
     * Sets <code>value</code> as attribute value for ABSTRACT using the alias name Abstract1.
     * @param value value to set the ABSTRACT
     */
    public void setAbstract1(ClobDomain value) {
        setAttributeInternal(ABSTRACT1, value);
    }

    /**
     * Gets the attribute value for TARGET_AUDIENCE using the alias name TargetAudience.
     * @return the TARGET_AUDIENCE
     */
    public String getTargetAudience() {
        return (String) getAttributeInternal(TARGETAUDIENCE);
    }

    /**
     * Sets <code>value</code> as attribute value for TARGET_AUDIENCE using the alias name TargetAudience.
     * @param value value to set the TARGET_AUDIENCE
     */
    public void setTargetAudience(String value) {
        setAttributeInternal(TARGETAUDIENCE, value);
    }

    /**
     * Gets the attribute value for EXPERIENCE_LEVEL using the alias name ExperienceLevel.
     * @return the EXPERIENCE_LEVEL
     */
    public String getExperienceLevel() {
        return (String) getAttributeInternal(EXPERIENCELEVEL);
    }

    /**
     * Sets <code>value</code> as attribute value for EXPERIENCE_LEVEL using the alias name ExperienceLevel.
     * @param value value to set the EXPERIENCE_LEVEL
     */
    public void setExperienceLevel(String value) {
        setAttributeInternal(EXPERIENCELEVEL, value);
    }

    /**
     * Gets the attribute value for GRANULARITY using the alias name Granularity.
     * @return the GRANULARITY
     */
    public String getGranularity() {
        return (String) getAttributeInternal(GRANULARITY);
    }

    /**
     * Sets <code>value</code> as attribute value for GRANULARITY using the alias name Granularity.
     * @param value value to set the GRANULARITY
     */
    public void setGranularity(String value) {
        setAttributeInternal(GRANULARITY, value);
    }

    /**
     * Gets the attribute value for DURATION using the alias name Duration.
     * @return the DURATION
     */
    public BigDecimal getDuration() {
        return (BigDecimal) getAttributeInternal(DURATION);
    }

    /**
     * Sets <code>value</code> as attribute value for DURATION using the alias name Duration.
     * @param value value to set the DURATION
     */
    public void setDuration(BigDecimal value) {
        setAttributeInternal(DURATION, value);
    }

    /**
     * Gets the attribute value for SUBMISSION_IDENTIFIER using the alias name SubmissionIdentifier.
     * @return the SUBMISSION_IDENTIFIER
     */
    public Integer getSubmissionIdentifier() {
        return (Integer) getAttributeInternal(SUBMISSIONIDENTIFIER);
    }

    /**
     * Sets <code>value</code> as attribute value for SUBMISSION_IDENTIFIER using the alias name SubmissionIdentifier.
     * @param value value to set the SUBMISSION_IDENTIFIER
     */
    public void setSubmissionIdentifier(Integer value) {
        setAttributeInternal(SUBMISSIONIDENTIFIER, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for DEMOS using the alias name Demos.
     * @return the DEMOS
     */
    public String getDemos() {
        return (String) getAttributeInternal(DEMOS);
    }

    /**
     * Sets <code>value</code> as attribute value for DEMOS using the alias name Demos.
     * @param value value to set the DEMOS
     */
    public void setDemos(String value) {
        setAttributeInternal(DEMOS, value);
    }

    /**
     * Gets the attribute value for NOTES using the alias name Notes.
     * @return the NOTES
     */
    public String getNotes() {
        return (String) getAttributeInternal(NOTES);
    }

    /**
     * Sets <code>value</code> as attribute value for NOTES using the alias name Notes.
     * @param value value to set the NOTES
     */
    public void setNotes(String value) {
        setAttributeInternal(NOTES, value);
    }

    /**
     * Gets the attribute value for COSPEAKERS using the alias name Cospeakers.
     * @return the COSPEAKERS
     */
    public String getCospeakers() {
        return (String) getAttributeInternal(COSPEAKERS);
    }

    /**
     * Sets <code>value</code> as attribute value for COSPEAKERS using the alias name Cospeakers.
     * @param value value to set the COSPEAKERS
     */
    public void setCospeakers(String value) {
        setAttributeInternal(COSPEAKERS, value);
    }


    /**
     * Gets the attribute value for the calculated attribute AbstractString.
     * @return the AbstractString
     */
    public String getAbstractString() {
       return getAbstract1().toString();
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link BthTagBindingView.
     */
    public RowIterator getBthTagBindingView() {
        return (RowIterator) getAttributeInternal(BTHTAGBINDINGVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link BthSpeakerView.
     */
    public RowIterator getBthSpeakerView() {
        return (RowIterator) getAttributeInternal(BTHSPEAKERVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link BthPlanningItemView.
     */
    public RowIterator getBthPlanningItemView() {
        return (RowIterator) getAttributeInternal(BTHPLANNINGITEMVIEW);
    }
}

